logging:
  level:
    root: INFO
    org.springframework.security: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demoDB
    username: demo
    password: mitdb
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

app:
  validation:
    bug:
      min-app-version: "1.10.15"
    feature:
      min-time-to-do: p10d
    max-title-length: 15
